name: Merge main to mine
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  merge_to_mine:
    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout mine branch
        uses: actions/checkout@v3
        with:
          ref: mine
      
      - name: Environment modify
        run: |
          
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "${{ secrets.RSA }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          git config --global user.email "${{ secrets.EMAILE }}"
          git config --global user.name "Miseryset"
          git remote rm origin
          git remote add origin git@github.com:Miseryset/ShortXCommands.git
                
      - name: Push
        run: |
          git checkout mine
          git merge origin/main || true
          git add .
          git commit -m "Sync_upstream"
          git push origin mine
          
